### PR TITLE
All 5 Guard Commander flavours

### PR DESCRIPTION
**Pull request by Cultiststeve**
Please review this for consistancy with other faction commanders.

I have included gst catagories for each commander.

Also, opinions if commisar/lord and platoon/company commanders should be done differently, as they are technicaly same data sheet?

### CODE REVIEW

**Comment by Cultiststeve** [comment]
Had to redo commander cats, stuff merge conflicts in xml files...

**Comment by Cultiststeve** [comment]
Fixes #170

**Comment by Mad-Spy** [comment]
- Commissar/Lord Commissar weapon point costs are incorrect.
- Typo in Refractor Field - _Commisar_

- Platoon/Company Commander missing Voice of Command ability.
- Platoon/Company Commander missing Officer keyword.
- Platoon/Company Commander weapon point costs are incorrect.
- Platoon/Company Commander Refractor Field has Lord Commissar text.
- Platoon/Company Commander missing Frag Grenades.
- Company Commander Senior Officer rule missing a full stop at the end.
- Company needs Laspistol set as default weapon.

- Tempestor Prime missing Militarum Tempestus and Officer keywords.
- Tempestor Prime weapon point costs are incorrect.

- All models need their keywords added to the GST and the Generalist SSEG to restrict Generalist abilities to those on their datasheet.

**Comment by Cultiststeve** [comment]
All issues identified are fixed (thanks for the thorough review  :) )

**Pull request merged**
